brotli = "yes"  # compression and woff2
dbus = "no"  # screensaver and portal
debug_symbols = "no"
deprecated = "no"
execinfo = "no"
fontconfig = "yes"  # system fonts
graphite = "yes"
lto = "all"
minizip = "no"  # zip support
module_astcenc_enabled = "no"  # adaptive scalable data compression format
module_basis_universal_enabled = "yes"
module_bmp_enabled = "no"  # BMP file format
module_camera_enabled = "no"  # windows and macos camera access
module_csg_enabled = "no"  # 3D csg boxes
module_cvtt_enabled = "no"  # yet another image format
module_dds_enabled = "no"  # ditto (but this is multiple)
module_denoise_enabled = "no"  # 3d lightmap denoising
module_enet_enabled = "no"  # multiplayer backend
module_etc_enabled = "no"  # image compression (again)
module_etcpak_enabled = "no"  # ^
module_freetype_enabled = "yes"  # font rendering
module_gdscript_enabled = "yes"
module_glslang_enabled = "yes"
module_gltf_enabled = "no"  # gltf loading
module_gridmap_enabled = "no"  # gridmap
module_hdr_enabled = "no"  # hdr images
module_jpg_enabled = "no"  # jpg images
module_jsonrpc_enabled = "no"  # godot/modules/jsonrpc/jsonrpc.cpp
module_lightmapper_rd_enabled = "no"
module_mbedtls_enabled = "no"  # TLS and crypto
module_meshoptimizer_enabled = "no"
module_minimp3_enabled = "no"  # mp3 player
module_mobile_vr_enabled = "no"
module_mono_enabled = "no"  # .NET
module_msdfgen_enabled = "no"
module_multiplayer_enabled = "no"  # godot multiplayer
module_navigation_enabled = "yes"  # navigation!!
module_noise_enabled = "yes"  # noise generation
openxr = "no"  # XR
module_openxr_enabled = "no"
module_ogg_enabled = "yes"
module_raycast_enabled = "no"  # lightmap raytracing
module_regex_enabled = "yes"
module_squish_enabled = "yes"  # S3TC lossy compression format
module_svg_enabled = "no"  # the svg support is bad, just prerender
module_text_server_fb_enabled = "no"  # the text server
module_text_server_adv_enabled = "yes"  # the cooler text server
module_tga_enabled = "no"  # more image formats
module_theora_enabled = "no"  # ogg theora video format
module_tinyexr_enabled = "no"  # image
module_upnp_enabled = "no"  # universal plug and play
module_vhacd_enabled = "no"  # 3d surface stuff
module_vorbis_enabled = "yes"  # vorbis audio
module_webp_enabled = "yes"  # lossy compression format
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"
module_xatlas_unwrap_enabled = "no"  # lightmapping stuff
module_zip_enabled = "no"
opengl3 = "yes"
optimize = "size"
production = "yes"
pulseaudio = "yes"  # linux audio
speechd = "no"  # tts
touch = "yes"  # touchscreen
udev = "yes"
vulkan = "no"  # use opengl3, this is the size build
use_volk = "no"
x11 = "yes"  # x11 rendering
